services:
  app:
    build:
      dockerfile: Dockerfile
    networks:
      - duke
    depends_on:
      - db
    command:
      - /bin/sh
      - -c
      - |
        knex migrate:latest
        npm run start
  db:
    image: postgres:18.3
    volumes:
      - db:/var/lib/postgresql
    networks:
      - duke
    env_file:
      - .env
volumes:
  db:
networks:
  duke:
