services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:4-24-trixie
    volumes:
      - ..:/workspace:cached
    networks:
      - duke
    command: sleep infinity
  db:
    image: postgres:18.3
    volumes:
      - db:/var/lib/postgresql
    networks:
      - duke
    env_file:
      - ../.env
volumes:
  db:
networks:
  duke:
